/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#ifndef	_Cert_H_
#define	_Cert_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cert */
typedef struct Cert {
	OCTET_STRING_t	 cert;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cert;
extern asn_SEQUENCE_specifics_t asn_SPC_Cert_specs_1;
extern asn_TYPE_member_t asn_MBR_Cert_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Cert_H_ */
#include <asn_internal.h>
