/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_SESeal;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module EsealModule in EsealModule.asn1 */
	&asn_DEF_SESeal,	
	0
};

