/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#ifndef	_SES_SealInfo_H_
#define	_SES_SealInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SES-Header.h"
#include <IA5String.h>
#include "SES-ESPropertyInfo.h"
#include "SES-ESPictureInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-SealInfo */
typedef struct SES_SealInfo {
	SES_Header_t	 header;
	IA5String_t	 esID;
	SES_ESPropertyInfo_t	 property;
	SES_ESPictureInfo_t	 picture;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_SealInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_SealInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SES_SealInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SES_SealInfo_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SES_SealInfo_H_ */
#include <asn_internal.h>
