/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#ifndef	_SES_SignInfo_H_
#define	_SES_SignInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Cert.h"
#include <OBJECT_IDENTIFIER.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-SignInfo */
typedef struct SES_SignInfo {
	Cert_t	 cert;
	OBJECT_IDENTIFIER_t	 signatureAlgorithm;
	BIT_STRING_t	 signData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_SignInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_SignInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SES_SignInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SES_SignInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SES_SignInfo_H_ */
#include <asn_internal.h>
