/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#include "SES-SealInfo.h"

asn_TYPE_member_t asn_MBR_SES_SealInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, header),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_Header,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, esID),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"esID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, property),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_ESPropertyInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"property"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, picture),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_ESPictureInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"picture"
		},
};
static const ber_tlv_tag_t asn_DEF_SES_SealInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SES_SealInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 2 }, /* header */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 1 }, /* property */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -2, 0 }, /* picture */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 1, 0, 0 } /* esID */
};
asn_SEQUENCE_specifics_t asn_SPC_SES_SealInfo_specs_1 = {
	sizeof(struct SES_SealInfo),
	offsetof(struct SES_SealInfo, _asn_ctx),
	asn_MAP_SES_SealInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SES_SealInfo = {
	"SES-SealInfo",
	"SES-SealInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SES_SealInfo_tags_1,
	sizeof(asn_DEF_SES_SealInfo_tags_1)
		/sizeof(asn_DEF_SES_SealInfo_tags_1[0]), /* 1 */
	asn_DEF_SES_SealInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SES_SealInfo_tags_1)
		/sizeof(asn_DEF_SES_SealInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SES_SealInfo_1,
	4,	/* Elements count */
	&asn_SPC_SES_SealInfo_specs_1	/* Additional specs */
};

