/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#include "SES-SignInfo.h"

asn_TYPE_member_t asn_MBR_SES_SignInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SignInfo, cert),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Cert,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cert"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SignInfo, signatureAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signatureAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SignInfo, signData),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signData"
		},
};
static const ber_tlv_tag_t asn_DEF_SES_SignInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SES_SignInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* signData */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* signatureAlgorithm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* cert */
};
asn_SEQUENCE_specifics_t asn_SPC_SES_SignInfo_specs_1 = {
	sizeof(struct SES_SignInfo),
	offsetof(struct SES_SignInfo, _asn_ctx),
	asn_MAP_SES_SignInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SES_SignInfo = {
	"SES-SignInfo",
	"SES-SignInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SES_SignInfo_tags_1,
	sizeof(asn_DEF_SES_SignInfo_tags_1)
		/sizeof(asn_DEF_SES_SignInfo_tags_1[0]), /* 1 */
	asn_DEF_SES_SignInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SES_SignInfo_tags_1)
		/sizeof(asn_DEF_SES_SignInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SES_SignInfo_1,
	3,	/* Elements count */
	&asn_SPC_SES_SignInfo_specs_1	/* Additional specs */
};

