/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#ifndef	_SES_ESPictureInfo_H_
#define	_SES_ESPictureInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-ESPictureInfo */
typedef struct SES_ESPictureInfo {
	IA5String_t	 type;
	OCTET_STRING_t	 data;
	long	 width;
	long	 height;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_ESPictureInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_ESPictureInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SES_ESPictureInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SES_ESPictureInfo_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SES_ESPictureInfo_H_ */
#include <asn_internal.h>
