/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#include "SES-Header.h"

static int asn_DFL_2_cmp(const void *sptr) {
	static const uint8_t defv[] = "ES";
	const IA5String_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	if(st->size == (sizeof(defv) - 1)
	&& memcmp(st->buf, &defv, sizeof(defv) - 1) == 0)
		return 0;
	return 1;
}
static int asn_DFL_2_set(void **sptr) {
	static const uint8_t defv[] = "ES";
	IA5String_t *st = *sptr;
	uint8_t *nstr = MALLOC(sizeof(defv));
	
	if(!nstr) return -1;
	memcpy(nstr, defv, sizeof(defv));
	
	if(st) {
		FREEMEM(st->buf);
	} else {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) { FREEMEM(nstr); return -1; }
	}
	st->buf = nstr;
	st->size = sizeof(defv) - 1;
	
	return 0;
}
asn_TYPE_member_t asn_MBR_SES_Header_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SES_Header, id),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp,	/* Compare DEFAULT "ES" */
		&asn_DFL_2_set,	/* Set DEFAULT "ES" */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_Header, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_Header, vid),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vid"
		},
};
static const int asn_MAP_SES_Header_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_SES_Header_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SES_Header_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 1 }, /* id */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 2, -1, 0 } /* vid */
};
asn_SEQUENCE_specifics_t asn_SPC_SES_Header_specs_1 = {
	sizeof(struct SES_Header),
	offsetof(struct SES_Header, _asn_ctx),
	asn_MAP_SES_Header_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SES_Header_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SES_Header = {
	"SES-Header",
	"SES-Header",
	&asn_OP_SEQUENCE,
	asn_DEF_SES_Header_tags_1,
	sizeof(asn_DEF_SES_Header_tags_1)
		/sizeof(asn_DEF_SES_Header_tags_1[0]), /* 1 */
	asn_DEF_SES_Header_tags_1,	/* Same as above */
	sizeof(asn_DEF_SES_Header_tags_1)
		/sizeof(asn_DEF_SES_Header_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SES_Header_1,
	3,	/* Elements count */
	&asn_SPC_SES_Header_specs_1	/* Additional specs */
};

