/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#include "SES-ESPropertyInfo.h"

static asn_TYPE_member_t asn_MBR_certList_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Cert,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_certList_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_certList_specs_4 = {
	sizeof(struct certList),
	offsetof(struct certList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_certList_4 = {
	"certList",
	"certList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_certList_tags_4,
	sizeof(asn_DEF_certList_tags_4)
		/sizeof(asn_DEF_certList_tags_4[0]), /* 1 */
	asn_DEF_certList_tags_4,	/* Same as above */
	sizeof(asn_DEF_certList_tags_4)
		/sizeof(asn_DEF_certList_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_certList_4,
	1,	/* Single element */
	&asn_SPC_certList_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SES_ESPropertyInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SES_ESPropertyInfo, type),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_ESPropertyInfo, name),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_ESPropertyInfo, certList),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_certList_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_ESPropertyInfo, createDate),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"createDate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_ESPropertyInfo, validStart),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"validStart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_ESPropertyInfo, validEnd),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"validEnd"
		},
};
static const ber_tlv_tag_t asn_DEF_SES_ESPropertyInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SES_ESPropertyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* certList */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 3, 0, 2 }, /* createDate */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 4, -1, 1 }, /* validStart */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 5, -2, 0 } /* validEnd */
};
asn_SEQUENCE_specifics_t asn_SPC_SES_ESPropertyInfo_specs_1 = {
	sizeof(struct SES_ESPropertyInfo),
	offsetof(struct SES_ESPropertyInfo, _asn_ctx),
	asn_MAP_SES_ESPropertyInfo_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SES_ESPropertyInfo = {
	"SES-ESPropertyInfo",
	"SES-ESPropertyInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SES_ESPropertyInfo_tags_1,
	sizeof(asn_DEF_SES_ESPropertyInfo_tags_1)
		/sizeof(asn_DEF_SES_ESPropertyInfo_tags_1[0]), /* 1 */
	asn_DEF_SES_ESPropertyInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SES_ESPropertyInfo_tags_1)
		/sizeof(asn_DEF_SES_ESPropertyInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SES_ESPropertyInfo_1,
	6,	/* Elements count */
	&asn_SPC_SES_ESPropertyInfo_specs_1	/* Additional specs */
};

