/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#ifndef	_SES_Header_H_
#define	_SES_Header_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-Header */
typedef struct SES_Header {
	IA5String_t	*id	/* DEFAULT ES */;
	long	 version;
	IA5String_t	 vid;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_Header_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_Header;
extern asn_SEQUENCE_specifics_t asn_SPC_SES_Header_specs_1;
extern asn_TYPE_member_t asn_MBR_SES_Header_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SES_Header_H_ */
#include <asn_internal.h>
