/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EsealModule"
 * 	found in "EsealModule.asn1"
 */

#include "SESeal.h"

static asn_TYPE_member_t asn_MBR_SESeal_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SESeal, esealInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_SealInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"esealInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SESeal, signInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_SignInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_SESeal_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SESeal_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* esealInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* signInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_SESeal_specs_1 = {
	sizeof(struct SESeal),
	offsetof(struct SESeal, _asn_ctx),
	asn_MAP_SESeal_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SESeal = {
	"SESeal",
	"SESeal",
	&asn_OP_SEQUENCE,
	asn_DEF_SESeal_tags_1,
	sizeof(asn_DEF_SESeal_tags_1)
		/sizeof(asn_DEF_SESeal_tags_1[0]), /* 1 */
	asn_DEF_SESeal_tags_1,	/* Same as above */
	sizeof(asn_DEF_SESeal_tags_1)
		/sizeof(asn_DEF_SESeal_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SESeal_1,
	2,	/* Elements count */
	&asn_SPC_SESeal_specs_1	/* Additional specs */
};

